version: '3.9'

services:
  db:
    image: 'bitnami/postgresql:17.4.0'
    environment:
      POSTGRESQL_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
